# DESCRIPTION: Github actions config

name: coverage

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * 0' # weekly

env:
  CI_OS_NAME: linux
  CI_COMMIT: ${{ github.sha }}
  CCACHE_COMPRESS: 1
  CCACHE_DIR: ${{ github.workspace }}/.ccache
  CCACHE_MAXSIZE: 2Gi  # 2GiB for clang and gcc, 4GiB in total
  COVERAGE: 1
  CI_BUILD_STAGE_NAME: test

jobs:
  buildjob:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: verilator/verilator/.github/actions/coverage-build

  test-dist:
    needs: buildjob
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: verilator/verilator/.github/actions/coverage-build
    - run: bash TESTS=coverage-dist ci/ci-script.bash

  test-vlt-0:
    needs: buildjob
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: verilator/verilator/.github/actions/coverage-build
    - run: bash TESTS=coverage-vlt-0 ci/ci-script.bash

  test-vlt-1:
    needs: buildjob
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: verilator/verilator/.github/actions/coverage-build
    - run: bash TESTS=coverage-vlt-1 ci/ci-script.bash

  test-vlt-2:
    needs: buildjob
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: verilator/verilator/.github/actions/coverage-build
    - run: bash TESTS=coverage-vlt-2 ci/ci-script.bash

  test-vlt-3:
    needs: buildjob
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: verilator/verilator/.github/actions/coverage-build
    - run: bash TESTS=coverage-vlt-3 ci/ci-script.bash

  test-vltmt-0:
    needs: buildjob
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: verilator/verilator/.github/actions/coverage-build
    - run: bash TESTS=coverage-vltmt-0 ci/ci-script.bash

  test-vltmt-1:
    needs: buildjob
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: verilator/verilator/.github/actions/coverage-build
    - run: bash TESTS=coverage-vltmt-1 ci/ci-script.bash

  test-vltmt-2:
    needs: buildjob
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: ./verilator/verilator/.github/actions/coverage-build
    - run: bash TESTS=coverage-vltmt-2 ci/ci-script.bash

  test-vltmt-3:
    needs: buildjob
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: ./verilator/verilator/.github/actions/coverage-build
    - run: bash TESTS=coverage-vltmt-3 ci/ci-script.bash
